project:
  type: website
  output-dir: _site

website:
  title: "Title TBD"
  site-url: "https://raymonddanked.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Posts
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    html-math-method: katex
    code-copy: true
    highlight-style: github